### ISSUE TITLE
Moderator tools

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1322]
- [x] Merging doc. See also API issue https://github.com/c2corg/v6_api/issues/386
- [x] Deleting doc. See also API issue https://github.com/c2corg/v6_api/issues/465
- [x] Reset geometry for a route/outing. See also https://github.com/c2corg/v6_ui/issues/1120.

**Comment by loicperrin** [comment]
See §9 (p50) of RFP. I think there is also another issue on this subject.

**Comment by loicperrin** [comment]
- [ ] Tool for reporting a problem -> see #306 and #317

**Comment by asaunier** [comment]
> Tool for reporting a problem -> see #306 and #317

@loicperrin That looks not that prioritary. I recommend to keep the issues distinct.

**Comment by desnoes** [comment]
History of association (usefull tool for moderators) is already handled by #193

**Comment by desnoes** [comment]
I tested the merge between 2 documents: the associated documents (route and WP) of the source are correctly associated with the target document.
