### ISSUE TITLE
TODO images UI

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#166]
* [x] Add view/templates for images (including list and editing page)
* [x] Set an uploading directive (see #164)
* [x] List associated images in document view pages (perhaps in list pages as well)
* [x] Add a slideshow to view the images full size when clicking on thumbnails (for instance in a doc view page) See https://github.com/c2corg/v6_ui/issues/167

**Comment by asaunier** [comment]
@ginold Is there still work to do related to this issue? Can we close it?
