### ISSUE TITLE
Issue(s) linked to new design

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1808]
To be completed

* [x] Maybe "Point de passage principal" could be closer to the card (or inside the card)?
And add a line between "Choisir comme point principal" and the "main waypoint" card. For instance https://www.camptocamp.org/routes/edit/54201/fr (low prio)
![point de passage principal](https://user-images.githubusercontent.com/19718055/33188501-9f5c0f46-d09a-11e7-9a69-5f6dfb094375.PNG)

* [ ] xreports home page : the map cannot be folded.

**Page d'accueil**
- [ ] On ne peut pas replier la section sur l'application mobile.

Je liste ici les petits soucis cosmétique que je vois. Chrome, écran 1200px.

- [ ] Bouton d'éditions un peu trop "collés" au corps de la page : 
<img src="https://forum.camptocamp.org/uploads/default/original/2X/2/234fdbfa7a0353ffe5fc18f0b43c0630c1133ea3.png" width="79" height="208">

<img src="https://forum.camptocamp.org/uploads/default/original/2X/a/a9a74fd68a0ce04cb3c19475ef884af65632afd6.png" width="272" height="32">

- [ ] h4 headers font size is bigger than h3 headers 

- [ ] on mobile, action description in feed is too long and always ellipsed
  
![screenshot_20171125-175706](https://user-images.githubusercontent.com/2234024/33503414-ead466b8-d6e3-11e7-8474-2ff42b616f94.png)

- [ ] should editiion map be expandable? If yes, buttons positioning should be improved

![screenshot_20171123-174521](https://user-images.githubusercontent.com/2234024/33504960-e7a5c210-d6e9-11e7-93fa-54559a9b5228.png)

 - [ ] empty associated outings section should have a default text
![screenshot_20171123-174849](https://user-images.githubusercontent.com/2234024/33505076-5b4c3d8e-d6ea-11e7-99a4-a8d2347addb1.png)

- [ ] Date is missing in the xreports cards in the home feed (it could be added below the title as for outings):
![capture du 2017-12-05 09-43-05](https://user-images.githubusercontent.com/1192331/33597770-b6d90fca-d9a0-11e7-91b7-9e32ff6e24bb.png)

- [ ] Initial author has been removed from outing cards listed in a route pages

- [x] ~~In  route list, the ratings are truncated in some cases :
https://www.camptocamp.org/routes#act=rock_climbing&crtyp=multi&bbox=-416959%252C4408805%252C1216958%252C6791194&orrat=X1%252CX4&rexpo=E1%252CE5&erat=I%252CV&rrat=2%252C9c&frat=2%252C9c&grat=F%252CED6&prat=P1%252CP4
As the ratings are important, it's better to wrap the rating line instead of hidden the end.~~
- [x] ~~license on mobile should have some text~~
![screenshot_20171125-085825](https://user-images.githubusercontent.com/2234024/33504876-829da040-d6e9-11e7-862c-4a7e250d8214.png)
- [x] ~~when editing an outing, participants cards need some love~~
![screenshot_20171123-174448](https://user-images.githubusercontent.com/2234024/33504992-140ccc86-d6ea-11e7-8696-d9033aeef7e7.png)
- [x] ~~when editing outing, associated routes cards should not a that grey background~~
![screenshot_20171123-174437](https://user-images.githubusercontent.com/2234024/33505037-3c7c1618-d6ea-11e7-9037-6fad11eb73f3.png)
* [x] ~~ Hovering cards no longer hilight them. As a result in the advanced search pages it is no longer possible to hilight the cards when hovering the corresponding feature on the map. ~~
* [x] ~~Quand on survole un itinéraire sur la carte (topoguide), la vignettes de l'itinéraire ne se grise plus comme sur la version précédente~~
![bug affichage cards](https://user-images.githubusercontent.com/19892089/33232215-5e574fce-d202-11e7-9152-7c483bbc34ee.png)
- [x] ~~Many sections are not correctly configured to collapse / expand. E.g. in xreports. And animation on arrow has been lost~~ > #1858 
- [x] ~~For an article, an old version content is hidden : https://www.camptocamp.org/articles/version/903357/fr/1438531
It's not a corner case, it occurs for all old versions of several articles (short, long, 2 versions, many versions,...).~~ > #1863
* [x] ~~Comments section is sometimes missing, see for instance https://www.camptocamp.org/outings/947661/fr/cret-du-boeuf~~ > #1859
![capture du 2017-11-24 11-17-16](https://user-images.githubusercontent.com/1192331/33205989-1f8ff86c-d109-11e7-84a3-83231d7d057c.png)
* [x] ~~The "archived version" warning is duplicated. See for instance  https://www.camptocamp.org/routes/version/201814/fr/781096~~ > #1861
![capture du 2017-11-24 17-24-14](https://user-images.githubusercontent.com/1192331/33218285-510a6f20-d13c-11e7-97d0-f81989ee4d7a.png)
- [x] ~~Quand on repli un bloc, la fleche reste vers le bas (voulu?)~~ > see PR #1858 
- [x] Incorrect forum URL in comments
~~For instance in https://www.demov6.camptocamp.org/routes/56921/fr/six-carro-plaisirs-d-automne
The initial "Post first comment" was OK and opened the demo forum.
But then clicking on the username or on the "continue discussion" button opens the prod forum.
Some hard-coded URL?~~ > handled by #1859 and its PR #1860
- [x] ~~On mobile, `.viewdoc` should hide overflow~~ > #1845 
- [x] ~~xreports personal informations section has no background~~ > #1847
- [x] ~~on mobile, view page does hide the bottom of the content~~ > #1856

**Comment by stef74** [comment]
- [ ]

**Comment by asaunier** [comment]
* [ ] Incorrect forum URL in comments

For instance in https://www.demov6.camptocamp.org/routes/56921/fr/six-carro-plaisirs-d-automne
The initial "Post first comment" was OK and opened the demo forum.
But then clicking on the username or on the "continue discussion" button opens the prod forum.
Some hard-coded URL?

* [ ] cards are poorly rendered in the "friends" page https://www.demov6.camptocamp.org/following

![capture du 2017-11-02 10-54-02](https://user-images.githubusercontent.com/1192331/32319986-910e8d54-bfbc-11e7-9394-c0eee70ecf4f.png)

**Comment by loicperrin** [comment]
[] Y a quand même un autre truc qui me gêne (déjà signalé par Bubu je crois) : les images dans l'en-tête des docs sont bizarrement cadrées. Voir par exemple : http://176.31.110.197:6553/routes/54526/fr/ancohuma-face-w ou http://176.31.110.197:6553/waypoints/37355/fr/mont-blanc (mais j'en ai vu plusieurs des comme ça). En l'état (ce pb ne doit pas être simple), je crois que je préfère qu'il n'y ait pas d'image du tout en-tête des docs (à voir si c'est facile de l'enlever provisoirement). En plus j'ai l'impression que ça ralentit l'affichage de la page. (medium prio)

[] in a route list, the rating is not displayed for one route, maybe because there is no max elevation:
![liste-iti](https://user-images.githubusercontent.com/19718055/32148295-f2d4690c-bcf4-11e7-953d-b17f97feeffd.PNG) (low prio)

[] Other little problem: on the outings page, dates are cut when the map is displayed on my (small) screen
![liste-sorties](https://user-images.githubusercontent.com/19718055/32251881-3e4af942-be93-11e7-86c7-685da24d0e16.PNG) (medium prio)

[] Maybe "Point de passage principal" could be closer to the card (or inside the card)?
And add a line between "Choisir comme point principal" and the "main waypoint" card. (low prio)

**Comment by stef74** [comment]
[ ] home topguide (low)

**Comment by cbeauchesne** [comment]
Je liste ici les petits soucis cosmétique que je vois. Chrome, écran 1200px.

* Liste des itinéraires, vue en liste, petit chevauchage  : 
<img src="https://forum.camptocamp.org/uploads/default/original/2X/e/eaad2ec5e314c8e7d6ef4db27a45b3194cdb685c.png" width="155" height="110">

* https://www.demov6.camptocamp.org/areas/14407/fr/grandes-rousses-arves pas de photo = gros dandeau gris. à réduire?

* Bouton d'éditions un peu trop "collés" au corps de la page : 
<img src="https://forum.camptocamp.org/uploads/default/original/2X/2/234fdbfa7a0353ffe5fc18f0b43c0630c1133ea3.png" width="79" height="208">

* Quand on repli un bloc, la fleche reste vers le bas (voulu?)
<img src="https://forum.camptocamp.org/uploads/default/original/2X/a/a9a74fd68a0ce04cb3c19475ef884af65632afd6.png" width="272" height="32">

* petit chevauchage sur les points de passage dans la page iti (l'icone gagnerai à etre plus petite) 
<img src="https://forum.camptocamp.org/uploads/default/original/2X/b/b763b88fd2707400bf8924f3b2fbccd3c0cf5bfa.png" width="227" height="167">

**Comment by desnoes** [comment]
Le test d'annonce reste affiché en permanence sur toutes les pages même après l'avoir lu.

**Page d'accueil**
On ne peut pas replier la section sur l'application mobile.

**Création itinéraire**
Erreur d'affichage de la carte en preview (pas bloquant)
![bug preview route](https://user-images.githubusercontent.com/19892089/32590987-7f586bbe-c51d-11e7-9dc5-1b643df973d5.png)


**sortie**
Bug d'affichage: la vignette jaune déborde un peu sur le texte (non bloquant)
![bug affichage sortie](https://user-images.githubusercontent.com/19892089/32590994-8ad673aa-c51d-11e7-953f-506c437103cc.png)

**Comment by stef74** [comment]
1st PR to fix some issue #1823

**Comment by stef74** [comment]
Could you add an url for each issue to easly fix reproduce it.

**Comment by fbunoz** [comment]
In route list, the ratings are truncated in some cases : 
https://www.camptocamp.org/routes#act=rock_climbing&crtyp=multi&bbox=-416959%252C4408805%252C1216958%252C6791194&orrat=X1%252CX4&rexpo=E1%252CE5&erat=I%252CV&rrat=2%252C9c&frat=2%252C9c&grat=F%252CED6&prat=P1%252CP4
As the ratings are important, it's better to wrap the rating line instead of hidden the end.

**Comment by stef74** [comment]
For @all ... could you had checkbox on all identified point with url ex + screen size and navigator

**Comment by stef74** [comment]
@desnoes the preview map not working in prod also ?

**Comment by desnoes** [comment]
@stef74: map is displayed correctly in prod.

**Comment by asaunier** [comment]
* [ ] Comments section is sometimes missing, see for instance https://www.camptocamp.org/outings/947661/fr/cret-du-boeuf
![capture du 2017-11-24 11-17-16](https://user-images.githubusercontent.com/1192331/33205989-1f8ff86c-d109-11e7-84a3-83231d7d057c.png)

**Comment by cbeauchesne** [comment]
h4 headers font size is bigger than h3 headers

**Comment by fbunoz** [comment]
For an article, an old version content is hidden : https://www.camptocamp.org/articles/version/903357/fr/1438531
It's not a corner case, it occurs for all old versions of several articles (short, long, 2 versions, many versions,...).

**Comment by asaunier** [comment]
- [ ] In the slideshow, images with no provided title have "undefined" as caption:
<img width="300" alt="capture d ecran 2017-11-28 a 23 35 39" src="https://user-images.githubusercontent.com/1192331/33348001-017282ac-d495-11e7-9ae4-c895f89c7a4f.png">

Probably related to https://github.com/c2corg/v6_ui/pull/1810

**Comment by asaunier** [comment]
* [ ] Hovering cards no longer hilight them. As a result in the advanced search pages it is no longer possible to hilight the cards when hovering the corresponding feature on the map.

**Comment by brunobesson** [comment]
[x] On mobile, `.viewdoc` should hide overflow > #1845

**Comment by brunobesson** [comment]
> Hovering cards no longer hilight them. As a result in the advanced search pages it is no longer possible to hilight the cards when hovering the corresponding feature on the map.

More generally we have lost a lot of hovering feedback. This is missing also on the mobile version.

**Comment by brunobesson** [comment]
- [ ] on mobile, action description in feed is too long and always ellipsed
  
![screenshot_20171125-175706](https://user-images.githubusercontent.com/2234024/33503414-ead466b8-d6e3-11e7-8474-2ff42b616f94.png)

**Comment by brunobesson** [comment]
- [ ] xreports personal informations section has no background > #1847

**Comment by brunobesson** [comment]
- [ ] xreports personal informations section has no background > #1847

**Comment by brunobesson** [comment]
- [ ] Many sections are not correctly configured to collapse / expand. E.g. in xreports.

**Comment by brunobesson** [comment]
- [ ] license on mobile should have some text
![screenshot_20171125-085825](https://user-images.githubusercontent.com/2234024/33504876-829da040-d6e9-11e7-862c-4a7e250d8214.png)

**Comment by brunobesson** [comment]
- [ ] should editiion map be expandable? If yes, buttons positioning should be improved

![screenshot_20171123-174521](https://user-images.githubusercontent.com/2234024/33504960-e7a5c210-d6e9-11e7-93fa-54559a9b5228.png)

**Comment by brunobesson** [comment]
- [ ] when editing an outing, participants cards need some love
![screenshot_20171123-174448](https://user-images.githubusercontent.com/2234024/33504992-140ccc86-d6ea-11e7-8696-d9033aeef7e7.png)

**Comment by brunobesson** [comment]
- [ ] when editing outing, associated routes cards should not a that grey background
![screenshot_20171123-174437](https://user-images.githubusercontent.com/2234024/33505037-3c7c1618-d6ea-11e7-9037-6fad11eb73f3.png)

**Comment by brunobesson** [comment]
- [ ] in outings view, an empty weather section should not be displayed
![screenshot_20171123-173912](https://user-images.githubusercontent.com/2234024/33505175-a2437fb8-d6ea-11e7-8076-e20bffa3d0c6.png)

**Comment by stef74** [comment]
@brunobesson your help is "welkome" to fix some issue

**Comment by brunobesson** [comment]
@stef74 note that I have reported issues, and solved some in the meantime...

**Comment by asaunier** [comment]
* [ ] Date is missing in the xreports cards in the home feed (it could be added below the title as for outings):
![capture du 2017-12-05 09-43-05](https://user-images.githubusercontent.com/1192331/33597770-b6d90fca-d9a0-11e7-91b7-9e32ff6e24bb.png)

**Comment by asaunier** [comment]
- [ ] Initial author has been removed from outing cards listed in a route pages

**Comment by asaunier** [comment]
In outing pages, there is an activity filter for the associated routes. Eg. https://www.camptocamp.org/outings/950651/fr/le-chantonnet-tete-de-ferret-la-dotse-en-circuit

I don't think it was provided before the layout change. Not sure it is really useful since there is generally not that much routes associated to an outing.

**Comment by brunobesson** [comment]
- [x] ~~on mobile, view page does hide the bottom of the content > #1856~~

**Comment by brunobesson** [comment]
@asaunier I do not observe this behaviour related to images without comment, e.g. http://localhost:6555/outings/828283/fr/jo-part-a-cetamol
Could you please provide me with a link to page for your screenshot?

**Comment by stef74** [comment]
@brunobesson which point I have you plan to NOT handle ;-)

**Comment by brunobesson** [comment]
I have no particular plan. Some are quite easy or I f*** want it to be solved, so I work on it.
If you plan to work on a specific point, just assign it to yourself (create the issue first of course) and I won't touch it.

**Comment by asaunier** [comment]
*[ ] When associating a WP to a route, since the WP listing section is placed in a quite remote location compared to the association tool, it's hard to realize that the associating has actually worked (it seems nothing happened whereas the WP has been added somewhere else).

Perhaps we could have several instances of the association tool (``app-add-association`` directive), with one at the bottom of the WP list. It is possible to adapt the list of searched document types using the ``dataset`` attribute, eg. ``dataset="wrcbx"``
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/view.html#L167
See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/utils.js#L8-L33 for the list of doctypes.

**Comment by asaunier** [comment]
* [ ] "outing" badge (near the title) is not translated in outing pages => it seems the string is not available in Transifex, most likely because it has not been marked as "translate"-able in the templates
* [ ] activity icons are no longer displayed near the outing page titles despite they are added in the templates: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/outing/view.html#L97

**Comment by asaunier** [comment]
* [ ] When the mouse cursor hovers a data block (figures, description, etc.) in a document (route, outing, etc.) it turns to a pointer, which does not makes sense since the block is not clickable.
It is probably related to the ``ficontent`` class:
https://github.com/c2corg/v6_ui/blob/364c4f7f714533242ea874606c8506c75e74bcd1/less/viewdetails.less#L16
Example of use: https://github.com/c2corg/v6_ui/blob/78ef975cae6732c15d369366d210e7b21b6113b8/c2corg_ui/templates/route/view.html#L143

**Comment by stef74** [comment]
I'm not sure is a good idea to add improvement on this issue ... only for "bug". I try to do a new issue with point not fixed
