### ISSUE TITLE
Associations blocks improvements

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#191]
- [x] Make the main WP obvious
 - [x] + add a way to change what WP is the main one
- [x] Group WP by waypoint_type and make the waypoint_type appear (icon) [To decide/figure out according to the wireframes: show all associated WP at the same place or in several distinct places?]
- [x] Show associations as cards, see https://github.com/c2corg/v6_ui/issues/181
- [ ] Show WP hierarchy ("sommet/sur-sommet", etc.) => how to do this with cards? See https://github.com/c2corg/v6_ui/issues/348
- Add-Association tool:
 - [x] Support document ids (see https://github.com/c2corg/v6_api/issues/155)
 - [x] Do not enable to associate a document already associated (see https://github.com/c2corg/v6_ui/issues/184)
 - [ ] The dropdown list is cut off if not enough space below to render the full list of results => should display above in that case.
- Drop-Association tool:
 - [x] Add a confirmation before actually dropping the association
 - [x] Do not show the drop-association button for anonymous users

**Comment by asaunier** [comment]
* [ ] When an association is dropped, the card should be removed immediately or at least use a different style (grayed or white-shaded?) to make it obvious that the association-removal has succeeded.

**Comment by asaunier** [comment]
* [ ] Errors are not correctly managed (ie clear message). For instance when trying to associate a document that is already associated.

**Comment by asaunier** [comment]
* [ ] The association action is not explicit enough: if one associated a route to a WP with already many route, after picking a result in the association tool, nothing confirms the associated has succeeded (the new card may not be visible among all the other cards) => it looks like nothing happened.

**Comment by asaunier** [comment]
* [ ] The new cards is not clickable (and its layout is quite different/simplified from the other cards).

**Comment by ginold** [comment]
it becomes complicated to have :
- a card in mako template
- a card in html template
- a card in add-association directive

**Comment by asaunier** [comment]
We have to find a solution so that cards layout are consistent whereas the card is built in mako or using angular.

What about defining cards in Mako helpers and make them available to the various Mako templates? For directives, would it be possible to use the helper to generate a directive template with expressions instead of the final values?
