### ISSUE TITLE
Loading speed of pages could be increased

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#456]
The loading speed of the various pages is not excellent.

Things that could be improved:
- [x] Avoid loading all JS lib separately? See https://github.com/c2corg/v6_ui/issues/85 (PR in https://github.com/c2corg/v6_ui/pull/574)
- [x] Add pyramid caching. See https://github.com/c2corg/v6_ui/issues/144
- [ ] Create sprites for icons
- [x] Better caching headers for static files (not sure the JS/CSS files are correctly cached by the browser)  (PR in https://github.com/c2corg/v6_ui/pull/574)
- [x] Make sure some API requests are really needed (eg. #540 - PR in https://github.com/c2corg/v6_ui/pull/579 )

**Comment by stef74** [comment]
Cache browser are configured at 1 hour. Is probably too less.

Exploitez la mise en cache du navigateur pour les ressources suivantes pouvant être mises en cache :
http://c2corgv6.demo-camptocamp.com/node_modules//angular-cookies/angular-cookies.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//angular-gettext/dist/angular-gettext.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//angular-messages/angular-messages.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//angular-moment/angular-moment.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//angular-recaptcha/release/angular-recaptcha.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//angular/angular.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//blueimp-load-image/js/load-image.all.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//bootstrap-slider/dist/bootstrap-slider.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//bootstrap-slider/dist/css/bootstrap-slider.css (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//bootstrap/dist/css/bootstrap.min.css (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//bootstrap/dist/js/bootstrap.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//jquery/dist/jquery.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//moment/min/moment.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//ng-file-upload/dist/ng-file-upload.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//photoswipe/dist/default-skin/default-skin.css (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//photoswipe/dist/photoswipe-ui-default.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//photoswipe/dist/photoswipe.css (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//photoswipe/dist/photoswipe.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//slick-carousel/slick/ajax-loader.gif (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//slick-carousel/slick/slick-theme.css (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//slick-carousel/slick/slick.css (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//slick-carousel/slick/slick.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules//typeahead.js/dist/typeahead.bundle.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules/bootstrap/fonts/glyphicons-halflings-regular.woff2 (1 hour)
http://c2corgv6.demo-camptocamp.com/node_modules/moment/locale/fr.js (1 hour)
http://c2corgv6.demo-camptocamp.com/static/c887e3f/build/build.js (1 hour)
http://c2corgv6.demo-camptocamp.com/static/c887e3f/build/build.min.css (1 hour)
http://c2corgv6.demo-camptocamp.com/static/c887e3f/build/locale/fr/c2corg_ui.json (1 hour)
http://c2corgv6.demo-camptocamp.com/static/c887e3f/img/icon.png (1 hour)
http://c2corgv6.demo-camptocamp.com/static/c887e3f/img/loading.gif (1 hour)
http://c2corgv6.demo-camptocamp.com/static/c887e3f/img/logo.svg (1 hour)
http://c2corgv6.demo-camptocamp.com/static/c887e3f/lib/angular-bootstrap/ui-bootstrap-custom-1.3.2.min.js (1 hour)
http://c2corgv6.demo-camptocamp.com/static/c887e3f/lib/angular-bootstrap/ui-bootstrap-custom-tpls-1.3.2.min.js (1 hour)

**Comment by tsauerwein** [comment]
@stef74 1 hour is the default cache time, so far the caching has not been configured explicitly.

**Comment by tsauerwein** [comment]
Google's mod_pagespeed looks promising. It automatically merges JS/CSS files and rewrites links to JS/CSS/image files to include a hash, which is updated when the file changes.

https://developers.google.com/speed/pagespeed/module/
http://modpagespeed.com/
https://github.com/pagespeed/mod_pagespeed

@mfournier Do you have experiences with mod_pagespeed?

**Comment by asaunier** [comment]
Is is still possible to use mod_pagespeed since we now use gunicorn instead of apache?

**Comment by asaunier** [comment]
We could also **give the impression** the page loads faster by improving the page rendering:
* avoid the page elements jump because of the map, see https://github.com/c2corg/v6_ui/issues/551
* remove the grey shade that is displayed in front of the page when the page loading indicator runs => it gives the impression the page is not usable yet!

By the way could we replace this loading spinner image by an horizontal loading indicator on the top border of the page (like in github for instance)?

**Comment by asaunier** [comment]
Perhaps we could also move the menu HTML code at the end of the pages: it's more important that the main content is loaded first.
As for now it is loaded at the very beginning of the page: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L46

**Comment by asaunier** [comment]
> By the way could we replace this loading spinner image by an horizontal loading indicator on the top border of the page (like in github for instance)?

Something like https://chieffancypants.github.io/angular-loading-bar/ (but perhaps only works for ``$http`` requests?).

**Comment by asaunier** [comment]
See also https://github.com/c2corg/v6_ui/pull/925
