### ISSUE TITLE
WP3 UI status

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#57]
This issue lists what's OK and NOK with WP3 tasks (based upon the demo instance).

OK:
* WP list page with pagination and features on map (ditto for routes but no feature on the map)
* simple view page
* simple adding/editing page
* registering a new user
* logging in with a v6-created user (eg. testc2c/testc2c)
* switching interface lang
* saving interface lang choice
* basic simple search
* showing WP on maps (in list pages + view/editing page)
* basic history page

Still TODO/FIXME:
* ~~use HTTPS for the demo instance (optional)~~
* [x] use internal URL for UI-server-side requests to API (see #18 & #88)
* [x] redirecting to selected document in simple search (path error => sysadmin ticket created to ask for a dedicated vhost)
* [x] editing WP geometry on map in editing page (see https://github.com/c2corg/v6_ui/pull/86)
* [x] all auth-actions (logout, adding a WP, editing a WP) are refused in the demo instance (see https://github.com/c2corg/v6_api/issues/106)
* [x] logging in with a v5 user (see https://github.com/c2corg/v6_api/issues/98)
* [x] i18n selector: the selected lang list is not shown in the dropdown when there are translations for the languages names in the current language (eg. french). OK if no i18n is available for the current language. => seems to be fixed by #39 
* [x] some components are not actually translated (form validation messages). Dropdown labels might also have translation problems (see #40)
* [x] feedback system (to show error or confirmation messages to the user) (see #8 )
 * [x] use it for appropriate actions (see #112 )
* [x] updating a WP
* [x] interacting with WP features in the list page map
* [x] viewing archived version of a document
* [x] diff buttons in history page
* [x] diffing 2 versions of a document
* [x] showing the best lang-version in lists when a document is available in several languages
* [x] don't send geometry to API when editing a document if no change in the geom has been made (see #24)
* [ ] server side reprojection crashes on the demo instance (see #20)
* [x] creating a new translation (lang-version) of an existing document (see #80)
* association (WP-WP and WP-Route)
 * [x] API (see https://github.com/c2corg/v6_api/pull/125)
 * [ ] UI (see #143 )
* BB code (and other v5-used formating codes) support
 * [x] format standard BB code (on display) (see #121 )
 * [ ] custom tags (see #131 )
 * ~~editor in page editing (see #122)~~
* [x] discourse `shared` authentication
* [x] prevent unauth users from accessing the editing forms (see #103 )
* [x] some page titles are missing/incorrect (see https://github.com/c2corg/v6_ui/pull/113)
