### ISSUE TITLE
TODO just before Go Live

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#639]
- [ ] migration: check there is no image duplicate: https://github.com/c2corg/v6_api/issues/363#issuecomment-249872137
- [ ] check API keys
- [ ] update Google Analytics key
- [ ] update discourse domain name in posts, see https://github.com/c2corg/v6_forum/issues/32#issuecomment-248318602
- [ ] reactivate discourse google indexing in admin settings / security
- [ ] make sure the `robots.txt` and `robots meta` are OK, see https://github.com/c2corg/v6_ui/pull/784, revert "noindex" change in meta "robots" 7f91d79
- [ ] Link sitemap in `robots.txt`: http://stackoverflow.com/questions/14196801/sitemap-url-in-robots-txt
- [ ] switch the snow forecast mailing lists system to the v6 DB
- [ ] Revert https://github.com/c2corg/v6_api/commit/7e0fd123ce50ad15db6915de6ee581b8a919f1aa (see https://github.com/c2corg/v6_api/issues/363)
- ...

**Comment by stef74** [comment]
In this ticket action is needed few day before go live or only action during the Go Live ?

**Comment by asaunier** [comment]
During go live.
Or at least when the next upgrade is the production, not the demo.

Some changes can be done now if we are sure that the Basic Auth will not be removed on the demo before the go live: robots.txt etc.

**Comment by asaunier** [comment]
Closing the issue, all tasks have been moved to the GoLive Trello board.
