### ISSUE TITLE
Area documents

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#668]
Areas are available on the API side.
But not in the UI side, despite there are links towards those documents (for instance in the WP detail views).
Perhaps we should at least make the area detail views available?

Those documents are a bit special:
- creating a new area is not possible (at least to normal users)
- area documents may be edited by contributors, except their geometry (because it impacts all the geo-associations).

See for instance http://www.camptocamp.org/areas/14144/fr/maroc

TODO
- [x] simple detail view page (only a few attributes) with usual tools:
  - [x] "other langs"
  - [x] archive: crash because the API does not support the old versions of areas yet, see https://github.com/c2corg/v6_api/issues/410
  - [x] history
  - [x] diff: crash because the API does not support the old versions of areas yet, see https://github.com/c2corg/v6_api/issues/410
  - [ ] images => upload OK but associated images are not returned, see https://github.com/c2corg/v6_api/issues/412
- [x] show full geometry in detail view page (pb for complex regions? too big?)
- associations in detail view pages
  - [x] at first, only buttons opening the advanced search pages with an `a=1234` filter parameter
  - perhaps also a list of recent outings? => requires https://github.com/c2corg/v6_api/issues/412
- [x] simple edit form.
  - [x] The map should be shown only to moderators.
  - [x] preview
- [x] simple advanced search page with only 3 filters (title + type of region + quality) + "area" card
  - [x] No "create" button (or for moderators only??)
  - [ ] geometries and map filtering support => see https://github.com/c2corg/v6_api/issues/419
- [ ] add to simple search => see https://github.com/c2corg/v6_api/issues/419 and https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L58
- [x] tests
- [x] update URL of regions in detail view pages
- [ ] ~~basic sitemap page~~

**Comment by tsauerwein** [comment]
> area documents may be edited by contributors, except their geometry (because it impacts all the geo-associations).

Moderators can change the geometry, this is supported by the API.

**Comment by asaunier** [comment]
> Moderators can change the geometry, this is supported by the API.

OK. Does it update the geoassociations then?

It means that we could have a normal editing form for areas, the map directive being shown only for moderators.

And we would also skip the "create" button.

Concerning the detail view page:
* it's a standard wiki page
* not sure if associated WP/routes/outings cards should be shown (at least the 10 last ones) but we could have buttons opening the advanced search pages with ``#a=12345`` parameters, filtering on area 12345. Is such a filter already available?

**Comment by tsauerwein** [comment]
> OK. Does it update the geoassociations then?

Yes.

> ...but we could have buttons opening the advanced search pages with #a=12345 parameters, filtering on area 12345. Is such a filter already available?

Also yes.

**Comment by asaunier** [comment]
Great! I have updated the TODO accordingly.

**Comment by stef74** [comment]
can be close ?

**Comment by asaunier** [comment]
No, there are still uncomplete tasks listed in the initial comment: https://github.com/c2corg/v6_ui/issues/668#issue-180026487
