### ISSUE TITLE
Document attributes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#791]
This issue lists problems with missing/misplaced/incorrectly entitled attributes.
It might also be addressed in combination with the documents organisation issue https://github.com/c2corg/v6_ui/issues/449

Some points are fixed by https://github.com/c2corg/v6_ui/pull/851

## Waypoints
- [ ] ~~attribute 'Proéminence' really relevant?,~~ see https://github.com/c2corg/v6_ui/issues/788
- [ ] missing attribute `rock_types`, see https://github.com/c2corg/v6_ui/issues/789
- [x] for waypoint type `shelter`, field 'capacity_staffed' should not be displayed (because it is never staffed anyway), see https://github.com/c2corg/v6_ui/issues/798
- [ ] remove 'elevation' from waypoint type 'climbing_indoor'
## Routes
- [x] attribute `external_resources` (text field for book and web resources) is not displayed either in the detail view pages or in the editing form. OK in API https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L232 and in common https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py#L8 => must be added after https://github.com/c2corg/v6_ui/blob/addbe79c1076f4291e1293cbc0dee16f77f4abb2/c2corg_ui/templates/route/view.html#L129

**Comment by desnoes** [comment]
Waypoint 
- [ ] 'paragliding_takeoff' and 'paragliding_landing': field 'ground_types' is missing
- [ ] 'weather_station' : display issue in the 'Types & Styles' section. 2 fields are overlapping. Is the title 'Types & Styles' correct ?

**Comment by asaunier** [comment]
> Is the title 'Types & Styles' correct ?

@desnoes See https://github.com/c2corg/v6_ui/issues/705#issuecomment-256511717

**Comment by asaunier** [comment]
More WP attribute issues: https://github.com/c2corg/v6_ui/issues/825

**Comment by asaunier** [comment]
Additional points moved from https://github.com/c2corg/v6_ui/issues/411#issuecomment-247082807 (perhaps already addressed?):

- [ ] Rocher haute montagne: field 'longueur de l'itinéraire is missing.ex: http://c2corgv6.demo-camptocamp.com/routes/736982/de/essai-alpha-3-climbing

- [ ] Hiking, snowshoeing, VTT: field 'Hauteur des difficultés' is included while it was not considered in https://docs.google.com/spreadsheets/d/1p7-RakklDot9gFnciEGox75833zU0ZuC5pRAoLZKziY/edit#gid=1418510514
ex: http://c2corgv6.demo-camptocamp.com/routes/736986/fr/essai-alpha-3-vtt
http://c2corgv6.demo-camptocamp.com/routes/736985/fr/essai-alpha-3-snowshoeing

**Comment by fbunoz** [comment]
> I fully agree with your comment Alex. I would remove this field from the list, it is totally confusing.

There is no proeminence data base on line, only some excel sheet downloadable. We have a good summit database. It is useful to use this database to make a proeminence database.
Then, this field must not be removed.

**Comment by asaunier** [comment]
Moving here @loicperrin 's report: https://github.com/c2corg/v6_ui/issues/825#issue-186601768

Here are some problems with WP:
- [ ] the V5 field "Accès routier" should be migrated into the V6 field "Abstract" (which should be renamed "Acces routier" in case of WP = Access)
- [ ] the V6 field "Acces" should be renamed "Acces TC" (OK if we can do it in Transifex, but please check that it is not a common name used elsewhere)
- [ ] the field "Type de transport en commun" should be displayed only if field "Accessibilite en transport en commun" is different from null and "no service" and diplayed after it
- [ ] the field "Type de transport en commun" should not contain the field "remontée mécanique"
- [ ] ~~to georef the WP on the map, it would be easier if we can recenter the map on a city (as for the map in Topoguide page)~~ see #834
- [ ] for "produits locaux" WP, the field "Heures d'ouverture" should have the same name in display mode as in edition mode
- [ ] globally for several WP, some fields have not the same name in display mode as in edition mode (and probably this cannot be fixed with Transifex)
- [ ] for "produits locaux" WP, in edition mode, the title "Transport & Accès" should be suppressed (it does not contain anything)

**Comment by asaunier** [comment]
My reply to the report above: https://github.com/c2corg/v6_ui/issues/825#issuecomment-258115765

>  the V5 field "Accès routier" should be migrated into the V6 field "Abstract" (which should be renamed "Acces routier" in case of WP = Access)

That does not sound very relevant to me. The "abstract" attribute should be used for... abstracts, not access descriptions.

V5's "Accès routier" is actually the "description" attribute. In v6 it remains in the same "description" attribute (with the accommodation info): https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/parking.py#L84-L85

> the V6 field "Acces" should be renamed "Acces TC" (OK if we can do it in Transifex, but please check that it is not a common name used elsewhere)

Renaming the attribute title in Transifex will not work because the attribute is used for describing the public transportation way for "accesses" and the pedestrian way for "huts":
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/parking.py#L87
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/huts.py#L94

> the field "Type de transport en commun" should not contain the field "remontée mécanique"

"cable_car" is indeed listed as a possible value for public transportations:
https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L70

Has it been removed in the meantime from the google sheet?

Please note this value exists in v5:
https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/config/app.yml.in#L1962
and is migrated to v6:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/parking.py#L111

If this value is dropped in v6, I guess it must be ignored during the migration?

> to georef the WP on the map, it would be easier if we can recenter the map on a city (as for the map in Topoguide page)

I agree but that should be a dedicated issue, see https://github.com/c2corg/v6_ui/issues/834
Anyway it's low prio.

> globally for several WP, some fields have not the same name in display mode as in edition mode (and probably this cannot be fixed with Transifex)

Please list them in this issue.

**Comment by asaunier** [comment]
According to @fbunoz at https://github.com/c2corg/v6_api/issues/466#issuecomment-258192021

* [ ] the V6 access field must be shown in the WP document and in the edit form for the hut type (it is not the case for now).

**Comment by fbunoz** [comment]
> Has it been removed in the meantime from the google sheet?

There was an error in the google sheet, I added the option "cable car".
In V5, this option exists, but it is separated in the edit form.
In V6, we can put this option with others options for the first version.

**Comment by asaunier** [comment]
> In V6, we can put this option with others options for the first version.

Does it mean that we should do nothing about this point?

**Comment by loicperrin** [comment]
@fbunoz, can you remember what is the aim to have the option "cable car" as an option of pt_type field? It is not logical, as pt_type field is used to find access without using car.

**Comment by loicperrin** [comment]
>That does not sound very relevant to me. The "abstract" attribute should be used for... abstracts, not access descriptions.

>V5's "Accès routier" is actually the "description" attribute. In v6 it remains in the same "description" attribute (with the accommodation info): https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/parking.py#L84-L85

Ok, we can keep it in description (I report this because of the google sheet). But in this case, there should be a separator (blank line) between "Accès routier" and accommodation info and a title for accommodation info. Otherwise it is understandable.

**Comment by fbunoz** [comment]
> can you remember what is the aim to have the option "cable car" as an option of pt_type field?

The aim is to avoid to add a new boolean field for an option which can easily be managed with the multi-choice pt_field.
A multi-choice field with N options can be replaced by N boolean field, but it lighter for the code to use a multi-choice field.
In the V5, the difference with the cable_car option about other options, is that the cable_car option is always visible in the edit form, whereas the other options are visible only if pt_quality is filled and is different of "no service".
But in the V6, the pt_type field is always visible in the edit form. It is not a problem for the V6.0.

**Comment by loicperrin** [comment]
> The aim is to avoid to add a new boolean field for an option which can easily be managed with the multi-choice pt_field

But in V6 we have a field cable_car, so I think this value should be suppressed in pt_type field.
There seems to be a pb with migration: for example http://c2corgv6.demo-camptocamp.com/waypoints/edit/130862/fr should have "Remontées mécaniques" = "oui" (instead of "Pas d'information" and the checkbox "cable_car" checked)

**Comment by loicperrin** [comment]
> Please list them in this issue

I have listed them in https://github.com/c2corg/v6_ui/issues/705

**Comment by loicperrin** [comment]
>In V6 we have a field cable_car, so I think this value should be suppressed in pt_type field.
But there seems to be a pb with migration: for example http://c2corgv6.demo-camptocamp.com/waypoints/edit/130862/fr should have "Remontées mécaniques" = "oui" (instead of "Pas d'information" and the checkbox "cable_car" checked)

Ok for this @fbunoz?

**Comment by fbunoz** [comment]
- The value "cable_car" in WP is used for an access wich is a lift station.
- The boolean "cable_car" in routes is used to indicate that a cable car can be used to reduce the approach.

The 2 strings must be different to allow different translations. For exemple : lift_station i WP and cable_car in route.
The translation in french : 
- lift_station : Gare de remontée mécanique
- cable_car : Accès en remontée mécanique possible

**Comment by ginold** [comment]
`rock_types` is not missing, it is only available only for `climbing_outdoor`  as listed on commons. But on https://docs.google.com/spreadsheets/d/1Q_fl7UQKPMgzlnk5tvAGqrmesrwfA5gges8p25XLes8/edit#gid=1502780869 it's apparently for a few more waypoint types. Which is right?

**Comment by ginold** [comment]
@desnoes  

> 'weather_station' : display issue : 2 fields are overlapping.

you mean the text from select boxes overlapped in the editing form? it has been fixes in the meanwhile.
![screenshot from 2016-11-10 14-38-43](https://cloud.githubusercontent.com/assets/7814311/20178852/684a108c-a753-11e6-984c-ada84e443ab2.png)

**Comment by loicperrin** [comment]
>rock_types is not missing, it is only available only for climbing_outdoor

Ok for me (and the google sheet has to be modified). @desnoes ?

**Comment by desnoes** [comment]
> 'weather_station' : display issue : 2 fields are overlapping.
you mean the text from select boxes overlapped in the editing form? 

Yes, it was that.

>rock_types is not missing, it is only available only for climbing_outdoor
There are some inconsistency between the reference file (https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py) and the google spreadsheet. According to the reference, you are right this field is only available for climbing_outdoor.
The reference is given in

**Comment by stef74** [comment]
@desnoes could you do a synthesis ? It's not clear what is not working.

**Comment by loicperrin** [comment]
New problems detected:
- [ ] WP/deco-attero: field ground_type is missing
- [ ] WP/deco-attero: field altitude is missing. It is a blocking problem, as when trying to save such a WP, an error message is displayed "Champ obligatoire: Altitude", and the WP cannot be saved

**Comment by asaunier** [comment]
@loicperrin I notice that "excellent" is used both for the condition ratings and for the quality ratings (but the translations are different). 
https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L528
https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L602

* [ ] I think we'll have to rename one of these values, most likely the quality one. What do you suggest?

**Comment by loicperrin** [comment]
> I think we'll have to rename one of these values, most likely the quality one. What do you suggest?

"excellent" in quality ratings can be replaced by "very good".

**Comment by asaunier** [comment]
OK, added to https://github.com/c2corg/v6_common/pull/42/files

**Comment by asaunier** [comment]
I have changed to "great" because the blank space in "very good" is a problem (the qualities are used as CSS classes for the quality icons).

**Comment by stef74** [comment]
@asaunier What is the remaing job on this issue ? (WP deco/attero only ?) So I remove blocking

**Comment by ginold** [comment]
I have a Work In Progres PR with a few updates. If you @asaunier are working on the same issue, please be sure to check if we haven't done the same thing!

see #952

**Comment by asaunier** [comment]
@ginold I have not work in progress about this issue.

**Comment by ginold** [comment]
@loicperrin 

> WP/deco-attero: field altitude is missing

I have no problem with altitude for wp/deco-attero. Maybe it has been fixed in the meantime? please check :

![screenshot from 2016-11-21 10-14-05](https://cloud.githubusercontent.com/assets/7814311/20476844/459be96a-afd3-11e6-938b-06a3fce5176a.png)

**Comment by loicperrin** [comment]
> I have no problem with altitude for wp/deco-attero. Maybe it has been fixed in the meantime? please check :

Altitude field is now OK, but when saving I have the following error in both cases:
"2 is not a string: {'paragliding_rating': ''} : Cotation parapente"

**Comment by ginold** [comment]
This problem was fixed yesterday but I'm afraid it's not on the demo yet. Please be patient.

**Comment by ginold** [comment]
A few updates (not yet on the demo, so please don't test yet) :
+ remove 'capacity_staffed' for waypoint type 'shelter'
+ add 'route_length' for waypoint type 'rock_climbing'
+ remove 'difficulties_height' from route type 'mountain_biking', 'hiking' and 'snowshoeing' 
+ add 'ground_types' for waypoint type 'paragliding_landing' and 'paragliding_takeoff'
+ let save waypoint type 'climbing_indoor' without elevation

**Comment by loicperrin** [comment]
> Altitude field is now OK, but when saving I have the following error in both cases:
"2 is not a string: {'paragliding_rating': ''} : Cotation parapente"

Fixed!
(I have not tested other pbs).

**Comment by stef74** [comment]
Please use  checkbox more Easy to follow

**Comment by stef74** [comment]
@loicperrin Could check other point ? and close if is OK

**Comment by loicperrin** [comment]
These issues are not fixed (see previous comment):

ROUTES:
- [ ] Rocher haute montagne: field 'longueur de l'itinéraire is missing
- [ ] Hiking, snowshoeing, VTT: field 'Hauteur des difficultés' is included while it was not considered in https://docs.google.com/spreadsheets/d/1p7-RakklDot9gFnciEGox75833zU0ZuC5pRAoLZKziY/edit#gid=1418510514
  ex: http://c2corgv6.demo-camptocamp.com/routes/736986/fr/essai-alpha-3-vtt
  http://c2corgv6.demo-camptocamp.com/routes/736985/fr/essai-alpha-3-snowshoeing

WP:
- [ ] the V6 field "Acces" should be renamed "Acces TC" (OK if we can do it in Transifex, but please check that it is not a common name used elsewhere)
- [ ] the field "Type de transport en commun" should be displayed only if field "Accessibilite en transport en commun" is different from null and "no service" and displayed after it
- [ ] the field "Type de transport en commun" should not contain the field "remontée mécanique"
- [ ] for "produits locaux" WP, in edition mode, the title "Transport & Accès" should be suppressed (it does not contain anything)
- [ ]  **the V6 access field must be shown in the WP document and in the edit form for the hut type (it is not the case for now) -> this one is blocking (migration pb!). See for example: http://www.demov6.camptocamp.org/waypoints/104163/fr/refuge-du-promontoire compared to the same WP in V5 (data are missing).**

Some issues are "low prio", but the last one is blocking. So maybe it would be better to put it in a dedicated issue?

**Comment by desnoes** [comment]
ROUTES:
- [ ] Rocher haute montagne: field 'longueur de l'itinéraire is missing
- [ ] Hiking, snowshoeing, VTT: field 'Hauteur des difficultés' is included while it was not considered in https://docs.google.com/spreadsheets/d/1p7-RakklDot9gFnciEGox75833zU0ZuC5pRAoLZKziY/edit#gid=1418510514

The correct reference for fiel associated to routes is not the google spreadsheet. They are listed here: https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py
According to this reference, there is no problem. The field 'longueur de l'itinéraire' does not belong to the 'rock_climbing' structure. Similarly, 'Hauteur des difficultés' is not defined for hiking, snowshoeing and VTT.

**Comment by tsauerwein** [comment]
> the V6 access field must be shown in the WP document and in the edit form for the hut type (it is not the case for now) -> this one is blocking (migration pb!). See for example: http://www.demov6.camptocamp.org/waypoints/104163/fr/refuge-du-promontoire compared to the same WP in V5 (data are missing).

The field is migrated correctly. It is simply not returned.

```
select wl.access
from guidebook.documents_locales l join guidebook.waypoints_locales wl on l.id = wl.id
where l.document_id = 104163;
```

**Comment by asaunier** [comment]
> The correct reference for fiel associated to routes is not the google spreadsheet. They are listed here: https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py
According to this reference, there is no problem. The field 'longueur de l'itinéraire' does not belong to the 'rock_climbing' structure. Similarly, 'Hauteur des difficultés' is not defined for hiking, snowshoeing and VTT.

@stef74 @loicperrin @desnoes Could you please update your comments/todo list in order to give use clear and precise instructions. According to your messages I don't really understand what we should really do.

Could you also create a dedicated issue for tasks that are really needed before golive?

Thanks :)

**Comment by loicperrin** [comment]
> The field is migrated correctly. It is simply not returned.

So it is not blocking for GoLive, but it is "high prio" to display/edit this field.

> Could you please update your comments/todo list in order to give use clear and precise instructions

Done in my previous comment.

**Comment by stef74** [comment]
@loicperrin @desnoes could you do a synthesis what is missing and close this too big issue and reopen new issue.

**Comment by desnoes** [comment]
Here are the issues that still remain (i have created dedicated issues for each of them):
- The access field must be shown in the WP document and in the edit form for the hut type => #1215 
- WP Local product : remove "Transport & Accès" section => #938 
- The field "Type de transport en commun" should not contain the field "remontée mécanique" => #1214 
-  the field "Type de transport en commun" should be displayed only if field "Accessibilite en transport en commun" is different from null and "no service" and displayed after it => #1217
- WP 'Acces': the field "Accès" should be renamed "Accès TC" (OK if we can do it in Transifex, but please check that it is not a common name used elsewhere) => #1218
